### ISSUE TITLE
There is a bug about ferry

### ISSUE THREAD

**Issue by HanYaTails** [false-spring/gbfr-logs#102]
I noticed that in other players' logs, ferry's dps will be much lower then what the ferry player's logs displayed. It seems that the number of hits of "Umlauf" has a large different between the ferry player's logs and other palyers' logs.

**Comment by false-spring** [comment]
Will close this for https://github.com/false-spring/gbfr-logs/issues/41 which has been a long issue for a while now but not a good fix I can implement right now
