### ISSUE TITLE
Is there a plan to support more languages in the future or is there already a plan for that?

### ISSUE THREAD

**Issue by RikoNeko** [false-spring/gbfr-logs#12]

**Comment by false-spring** [comment]
@RikoNeko

Yes! The upcoming 0.0.4 update will have the ability to support multiple languages. However, I won't be able to add the actual translations for all the different languages that Relink supports right away.

https://github.com/false-spring/gbfr-logs/pull/10 will add a translation file for simplified chinese.

**Comment by false-spring** [comment]
I added support for adding multiple languages in https://github.com/false-spring/gbfr-logs/releases/tag/0.0.4 

If anyone would like to add support for their language, look at https://github.com/false-spring/gbfr-logs/blob/cc2135b75ac89822f065c2241eaa19f9000297d2/src/lang/zh-CN.json#L1 as an example file!
