### ISSUE TITLE
"Delete All" button storage

### ISSUE THREAD

**Issue by sasagm8** [false-spring/gbfr-logs#128]
I'm afraid I might press "Delete All" by mistake, so is it possible to save it in "Settings"?

**Comment by false-spring** [comment]
@sasagm8 Just to let you know, when you click on "Delete All", it will give you a confirmation:

![image](https://github.com/false-spring/gbfr-logs/assets/60109619/21bd8a93-3289-48d7-9fd6-4c3cef16cc0c)

**Comment by sasagm8** [comment]
Sorry, thank you
