### ISSUE TITLE
Trojan hit on Virustotal

### ISSUE THREAD

**Issue by iMisakaRin** [false-spring/gbfr-logs#130]
https://imgur.com/jyeWfbR

Was looking for a dps meter since I want to improve my damage but when I checked the msi installer, I got this.

**Comment by false-spring** [comment]
Thanks for the report, this is usually a losing battle as GBFR Logs gets false positives regularly (by nature of what it does.), and I've gotten multiple Windows Defender false positive flags that I've had to manually resolve with Microsoft which usually takes a few days for them to re-analyze and mark the file as clean again.

That SHA-256 hash matches the MSI that I built myself, and all update builds are signed using my public key as well to ensure that they come from me.
