### ISSUE TITLE
Tweyen Combo Finisher 2 Charged is categorized as Combo Finisher 2 (charged is missing under Combo Finisher Charged)

### ISSUE THREAD

**Issue by yutttta** [false-spring/gbfr-logs#137]

**Comment by false-spring** [comment]
Unfortunately, it looks like the charged and uncharged versions of Combo Finisher 2 both share the same skill ID of `160`, while regular Combo Finisher 1/3 have different skill IDs for their charged vs. uncharged versions.

So currently, there's not a great way to separate the two. 😢
