### ISSUE TITLE
AI characters and playable character are named as GUEST

### ISSUE THREAD

**Issue by Siix-x** [false-spring/gbfr-logs#142]
The first 3 characters including the character I'm playing with are named GUEST. The last AI character appears as the main character. Charlotte is the character I'm playing.

![image](https://github.com/false-spring/gbfr-logs/assets/171474671/9548c7e2-81d6-4c55-ad0e-473b3abf68e4)

**Comment by false-spring** [comment]
Fixed in https://github.com/false-spring/gbfr-logs/commit/df7cd2965d8a3e95c693dd0dd1707a06616772f2
