### ISSUE TITLE
i have use before and now impossible

### ISSUE THREAD

**Issue by Pachalpha** [false-spring/gbfr-logs#143]
Hi !
i have use GBFR logs before 1.6.1, and now i try to reinstal but i have this message "C:\Users\me\Downloads\ZKg6DgUK.msi.part cannot be saved because the source file cannot be read." IDK what i need to open file .msi

**Comment by Jinsiepoo** [comment]
I have the same issue. I don't know if you have a fix for it.

**Comment by false-spring** [comment]
For these issues, it can happen when Microsoft Defender usually deletes / quarantines the file while you are downloading or installing.

Check to see if your anti-virus has any warnings, or refer to the instructions in https://github.com/false-spring/gbfr-logs/blob/main/README.md#frequently-asked-questions

**Comment by Jinsiepoo** [comment]
I read it all but nothing worked.
