### ISSUE TITLE
Using ID's Dragonform skills crashes the game with GBFR installed

### ISSUE THREAD

**Issue by Tactical96** [false-spring/gbfr-logs#144]
![Screenshot 2024-06-28 192956](https://github.com/false-spring/gbfr-logs/assets/26966370/5bfec601-b576-4498-86e1-f8761757eff9)

While using ID's Dragonform, if you use RB+X or RB+Y, there's a 50/50 chance to crash the game, not only for you, but for anyone using GBFR in the party.

GBFR version : 1.6.1
Granblue version : 1.3.2

**Comment by Tactical96** [comment]
It happens very frequently when fighting Proto Bahamut in the quest : The Tale of Bahamut's Rage. Only when casting RB+X or RB+Y while in ID's Dragonform.

**Comment by false-spring** [comment]
Fixed in https://github.com/false-spring/gbfr-logs/commit/572a6a080a9527cefae88c0ce32902eac1215ad7
