### ISSUE TITLE
Dynamically load language files instead of being baked into the executable

### ISSUE THREAD

**Issue by false-spring** [false-spring/gbfr-logs#15]
Currently, language files are built as part of the executable package. This can make it difficult for contributors to work and improving these translation files as they would have to setup a development environment.

Instead..

- Move the language files to a folder in the application installation folder, alongside the executable. (`/lang`)
- Watch the directory for changes using [tauri-plugin-fs-watch](https://github.com/tauri-apps/tauri-plugin-fs-watch)
- Update translation files in real-time to [i18next](https://github.com/false-spring/gbfr-logs/blob/cc2135b75ac89822f065c2241eaa19f9000297d2/src/i18n.ts#L18-L27)

This will allow any average user to modify the translation files and see their changes in real-time, making it easier for them to contribute changes to the project.

**Comment by xx0326** [comment]
[from translation software]
Hope i18n file use txt format,

[ZH]
希望多语言文件使用txt格式，

**Comment by false-spring** [comment]
> [from translation] Hope i18n file use txt format. Developers should not spend energy maintaining multiple languages. It is recommended to keep only the text comparison interface. The content is maintained by enthusiasts from different regions. [ZH] 希望多语言文件使用txt格式。 开发者不应该花精力去维护多语言。 建议只保留文本对比接口。 内容由来自不同地区的爱好者维护。

Yes, this will be easier in the new 0.0.5 version! https://github.com/false-spring/gbfr-logs/blob/main/src-tauri/lang/zh-CN.json
