### ISSUE TITLE
Parser injection appears to cause Stout Heart mitigation to apply twice.

### ISSUE THREAD

**Issue by x04ty29er** [false-spring/gbfr-logs#18]
I filed this issue in the GBFR-ACT repo https://github.com/nyaoouo/GBFR-ACT/issues/83
This one appears to have the same issue (though I guess since it is based on the same work, it would).

Let me know if you need more info and I'll provide what I can.

**Comment by x04ty29er** [comment]
I've been building from source so I think i picked up the fix.
In any case, I can confirm that it appears to be working as expected as of the latest main commit.

Thanks! I'll go ahead and close the issue.

**Comment by nyaoouo** [comment]
does this fix deal with attack judgment failed (missed), for example Cagliostro's Alexandria?

**Comment by false-spring** [comment]
> does this fix deal with attack judgment failed (missed), for example Cagliostro's Alexandria? Edit: i take a try and its well solved, good fix

Thank you for your work! @nyaoouo 🙇
