### ISSUE TITLE
Issue with Cagliostro's Damage Meter

### ISSUE THREAD

**Issue by wkit209** [false-spring/gbfr-logs#2]
Cagliostro's damage is showing as lower than it should. I don't know if this is happening with any other character.

Here is the picture of the overlay parser:
![image_2024-02-27_184641933](https://github.com/false-spring/gbfr-logs/assets/161537540/5ff70ca1-bd4b-4501-923b-df86e29ec9c3)

This is the actual parsed damage from dvorak321's parser (forked from nyaoouo):
![image_2024-02-27_184901054](https://github.com/false-spring/gbfr-logs/assets/161537540/f409d383-3dff-4394-a3f5-5686a1dec341)

Everyone else seems to be accurate except for Cagliostro's.

**Comment by false-spring** [comment]
This is possible due to the untracked damage of Cagliostro's Pain Train skill, since Ouroboros is counted as a separate damage source.

This should be fixed in the upcoming version. 👍
