### ISSUE TITLE
rackam aerial barrage hits count is incorrect

### ISSUE THREAD

**Issue by SauronSkywalker** [false-spring/gbfr-logs#34]
rackam aerial barrage hits count is incorrect
I see from my own statistics that hits are 34
My teammates see that my character's statistics show hits of 71
<img width="647" alt="1" src="https://github.com/false-spring/gbfr-logs/assets/59997490/eb38a830-1066-4f7c-8959-814c70cef918">
![2}](https://github.com/false-spring/gbfr-logs/assets/59997490/9b70851a-5e83-4dff-b7f0-b0c4df3d77fa)

**Comment by false-spring** [comment]
I think I mark this as not fixable currently. This is because we do not know how damage is synced in multiplayer, and there will be a difference in what other people will see compared to your own meter. This happens for all ACT / meters.

I will reopen if we figure out online multiplayer later on.
