### ISSUE TITLE
Skill Name Problem

### ISSUE THREAD

**Issue by WolffQuam** [false-spring/gbfr-logs#4]
I just tested the new 0.0.3 version, and I encountered 1 problem.
Some skills were not named correctly (It was for Yodarha in this case).
I'll add a screenshot. Hope this can help you ^^
![image](https://github.com/false-spring/gbfr-logs/assets/160700815/e760d279-3c4f-43e4-a4d0-7446fa0a22c1)

**Comment by false-spring** [comment]
Thanks for the report, I think there are a few missing skill names as you've pointed out that aren't in our list yet..

https://github.com/false-spring/gbfr-logs/blob/d16aeadc31edbabe8cc2bc813a2bfb1bafecd979/src/lang/en.json#L394-L420

**Comment by false-spring** [comment]
This will be fixed in the next 0.0.6 version as part of https://github.com/false-spring/gbfr-logs/pull/19
