### ISSUE TITLE
Garbled characters appear upon long Chinese nickname

### ISSUE THREAD

**Issue by wangzy77** [false-spring/gbfr-logs#43]
Thanks for your great work!

As the picture shows below, I played as IO and the other three are NPCs. When my nickname lenth is 2, its display is correct(in the later record). However when my nickname lenth is 10, garbled characters appear(in the earlier record).

![screenshot1](https://github.com/false-spring/gbfr-logs/assets/14155555/29aac3c6-b12c-4e25-aac1-fcc113806fe5)

**Comment by false-spring** [comment]
Fixed in https://github.com/false-spring/gbfr-logs/releases/tag/0.0.9
