### ISSUE TITLE
crash when run this exe

### ISSUE THREAD

**Issue by HisameKenshin** [false-spring/gbfr-logs#44]
just can not run this exe

**Comment by false-spring** [comment]
This is the latest 0.0.8 version, right? Can you screenshot what files are in your installation folder? (default: `C:\Program Files\GBFR Logs`)

**Comment by HisameKenshin** [comment]
![image](https://github.com/false-spring/gbfr-logs/assets/64142567/82cf60bd-3e9b-4b30-9154-3c2d7c997425)
thats all

**Comment by HisameKenshin** [comment]
yeah,thats 0.0.8 version.is that anything wrong?
