### ISSUE TITLE
Unable to run the installation program

### ISSUE THREAD

**Issue by Schatten57** [false-spring/gbfr-logs#46]
I am a Win10 Home Edition user, every time I try to run the installation program, a window will prompt me that "This app can’t run on your PC". Any possible reasons or solutions given would be appreciated.

**Comment by false-spring** [comment]
Please check Windows Defender for any reports of any automatic blocked notifications. There's been more false positive reports unfortunately with the increased number of downloads it seems..

I've attempted to submit a false positive report with Windows, so we will see if it gets better. 🙏 

Please comment again if you run into issues!

**Comment by Schatten57** [comment]
Okay, I solved the problem: I checked the Windows service settings on my PC and found that it had disabled the Windows installer service by default. After trying to turn it on and register the installation program, everything worked like charm.
