### ISSUE TITLE
Would there be an Open Source License?

### ISSUE THREAD

**Issue by Tanimodori** [false-spring/gbfr-logs#47]
I'd really like to appreciate the developers of this awesome project and contribute to this project. I just wonder that whether this project will be released under some Open Source Licenses like MIT, Apache or GPL? I think it would be great if this project is under those licenses for more contributors.

**Comment by false-spring** [comment]
Thanks for the concern! I have updated the repo with [an MIT license.](https://github.com/false-spring/gbfr-logs/blob/dee2529b9bfffcdb47fa5b7524cb6e3db703f8db/LICENSE) 👍
