### ISSUE TITLE
exe does not run

### ISSUE THREAD

**Issue by fottxt** [false-spring/gbfr-logs#57]
![스크린샷(793)](https://github.com/false-spring/gbfr-logs/assets/163779511/014a05cc-c6bd-4772-a501-8adf894b34b3)

I tried for several days but failed to run the exe.

GBFR Logs 0.0.9 version.

game is 1.1.2 version.

run as admin.

game is running.

I turned off all Windows Defender and anti-virus software and tried install and run exe.

there is no reaction. nothing happens

I know this is a very vague problem, but I would appreciate any help you can give me.

everyone is enjoying GBFR Logs, but I'm a loser :(

**Comment by false-spring** [comment]
Can you share which windows version you are on?

You can try these steps:
- See if you can uninstall the Microsoft Edge Webview2 Runtime.
- Install the latest one from Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download (Evergreen Bootstrapper should work here)

**Comment by fottxt** [comment]
OMG

I deleted Edge that I don't use

 I installed Edge, it started working!

thx bro! you are my hero :)
