### ISSUE TITLE
Add german translation

### ISSUE THREAD

**Issue by JumpingCoconut** [false-spring/gbfr-logs#58]
In addition to the other languages please add the JSON for german translation and add it as an option into the app.

**Comment by false-spring** [comment]
Will be added in 0.0.10: https://github.com/false-spring/gbfr-logs/tree/3ec3526ca619a3ba8f00280d604d6ec02c3f55e2/src-tauri/lang/ge

Next step is for someone to create a `ui.json` file to translate the rest of the UI.

Instructions are here: https://github.com/false-spring/gbfr-logs/tree/756055cc9b9d7ccc50cea7485ba2652f91fdf245/src-tauri/lang
