### ISSUE TITLE
hook.dll is not found when using `npm run tauri dev` as described in the readme

### ISSUE THREAD

**Issue by JumpingCoconut** [false-spring/gbfr-logs#59]
The instruction for devs in the readme is great, however when using `npm run tauri dev` the build fails under windows. It says `error could not compile typenum due to previous error`, the previous error being a missing `hook.dll`.

You need to build `hook.dll` manually and then move it into the `src-tauri` directory. If there was a way to automate this process using cargo it would be great.

The workaround I use is a batch file for now.
```batch
cd src-hook
cargo build
cd ..
copy target\debug\hook.dll src-tauri /Y
npm run tauri dev
```

**Comment by false-spring** [comment]
This should already be happening in the build.rs script here: https://github.com/false-spring/gbfr-logs/blob/c5ba6a8a0864f533645105d9b7e409a041455a5f/src-tauri/build.rs#L7-L18

But I think it's possible I may have broken it recently. 😬 I'll take a look.

**Comment by false-spring** [comment]
Fixed in https://github.com/false-spring/gbfr-logs/commit/504d4ea029b3e9e38f0b8aa63431be9832d86ec4
