### ISSUE TITLE
Add a function for the overlay to remember the position and size after closing.

### ISSUE THREAD

**Issue by dtranjack** [false-spring/gbfr-logs#86]
Is there a way to make the overlay remember the position and the size I resized/set it to? currently on 0.0.10 whenever I close the program completely and reopen it, it just defaults back to the default size and position on the screen, making the user resize and reposition it every time.

**Comment by false-spring** [comment]
This is definitely a bug and not intended. The position/size should be saved and restored when you relaunch the application. I'll investigate to see if it's a quick fix for the next release.
